### PR TITLE
Adding ssl cert configuration options

### LINKED ISSUE #65: Elasticsearch collector support for self-signed certificates
The Elasticsearch collector fails while attempting to verify a self-signed cert:
`[MainThread:ElasticSearchCollector:ERROR] https://127.0.0.1:9200/_nodes/_local/stats: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>`

### LINKED ISSUE #68: Elasticsearch collector SSL certificate verification should be an optional config

### PR DESCRIPTION
**Pull request by rclagett**
Closes #65

### CODE REVIEW

**Comment by TheConnMan** [comment]
Do you have recommended steps on how to test this?

**Comment by rclagett** [comment]
@TheConnMan Run an ES cluster over https, jam these changes in elasticsearch.py, and set `scheme` to https, `ssl_check_hostname` to True and `ssl_verify_mode` to ssl.CERT_REQUIRED or ssl.CERT_NONE in ElasticSearchCollector.conf

**Comment by Grumblesmith** [comment]
@TheConnMan I tested https using the AWS Elasticsearch Service, if that helps.

**Comment by TheConnMan** [comment]
Wonderful, thanks.

**Review by TheConnMan — APPROVED** [review]

**Pull request merged**
