### PR TITLE
Heartbeat Check

### PR DESCRIPTION
**Pull request by TheConnMan**
Implement a true heartbeat check using the new Checks API.

I'm not excited about coupling the Netuitive Handler config into the base Collector config, but I think this will be necessary for other check implementations as well. Otherwise the Metricly URL and API key need to be duplicated into the collector config.

### CODE REVIEW

**Comment by Grumblesmith** [comment]
I don't see any changes to the https://github.com/Netuitive/netuitive-diamond/blob/master/src/diamond/handler/netuitive_handler.py or any new netuitive checks handler. Where is the netuitive.Check defined?

**Comment by TheConnMan** [comment]
`netuitive.Check` comes from the Python client lib: https://github.com/Netuitive/netuitive-client-python/pull/16

**Comment by Grumblesmith** [comment]
Gotcha. Rather than importing the config in the collector to get the url and key, would it be better to flush the checks through the handler, which already has the config? Are there any downsides to that?

**Comment by TheConnMan** [comment]
No because of the structure of this project. The only interaction between collectors and handlers is metric publishing which cycles through all handlers in a very structured, metric centric way. Checks differ from that formula so my choices were:
- Add a whole new, custom route for checks to pipe through and only implement logic for the Netuitive handler
- Break outside the normal workflow and pull these configs

Honestly when I implemented this I realized the Netuitive agent probably isn't the best place for these, but is a good starting point.

**Review by Grumblesmith — APPROVED** [review]
Fair enough. If this is the way we have to do it, then this is the way we have to do it.

**Review by rclagett — APPROVED** [review]

**Pull request merged**
